server {
    listen 80 default;

    location /live {
        proxy_pass http://10.0.0.2:80/api/scene/rectr;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Authorization "Basic YWRtaW46cGFzcw==";
    }

    location / {
        proxy_pass http://127.0.0.1:8083/;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:8082/api/;
    }
}
